import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/localization/app_strings.dart';
import '../../../../core/providers/currency_provider.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/utils/currency_formatter.dart';
import '../../../../core/widgets/app_overflow_menu.dart';
import 'widgets/trade_card_selector_dialog.dart';

class TradeEvaluatorScreen extends ConsumerStatefulWidget {
  const TradeEvaluatorScreen({super.key});

  @override
  ConsumerState<TradeEvaluatorScreen> createState() => _TradeEvaluatorScreenState();
}

class _TradeEvaluatorScreenState extends ConsumerState<TradeEvaluatorScreen> {
  final List<TradeCardItem> _yourCards = [];
  final List<TradeCardItem> _theirCards = [];

  double get _yourTotal => _yourCards.fold(0.0, (acc, c) => acc + c.valueBrl);
  double get _theirTotal => _theirCards.fold(0.0, (acc, c) => acc + c.valueBrl);

  void _addYourCard(double exchangeRate) async {
    final item = await showTradeCardSelector(context, exchangeRate: exchangeRate, allowCollection: true);
    if (item != null) {
      setState(() => _yourCards.add(item));
    }
  }

  void _addTheirCard(double exchangeRate) async {
    final item = await showTradeCardSelector(context, exchangeRate: exchangeRate, allowCollection: false);
    if (item != null) {
      setState(() => _theirCards.add(item));
    }
  }

  void _copyTradeSummary(AppStrings strings, bool isUsd, double exchangeRate) {
    final diff = _theirTotal - _yourTotal;
    final buffer = StringBuffer();
    final header = strings.tradeEvaluationHeader;
    buffer.writeln('=== $header (WurmDex) ===');
    buffer.writeln('\n${strings.tradeLeftLabel} ${strings.tradeYouSend} (${strings.cardsCount(_yourCards.length)}):');
    for (final c in _yourCards) {
      final priceStr = isUsd
          ? CurrencyFormatter.toUsd(c.valueBrl / exchangeRate)
          : CurrencyFormatter.toBrl(c.valueBrl);
      buffer.writeln(' - ${c.name} (${c.setName}) : $priceStr');
    }
    final yourTotalStr = isUsd
        ? CurrencyFormatter.toUsd(_yourTotal / exchangeRate)
        : CurrencyFormatter.toBrl(_yourTotal);
    buffer.writeln('${strings.totalSent}: $yourTotalStr');

    buffer.writeln('\n${strings.tradeRightLabel} ${strings.tradeYouReceive} (${strings.cardsCount(_theirCards.length)}):');
    for (final c in _theirCards) {
      final priceStr = isUsd
          ? CurrencyFormatter.toUsd(c.valueBrl / exchangeRate)
          : CurrencyFormatter.toBrl(c.valueBrl);
      buffer.writeln(' - ${c.name} (${c.setName}) : $priceStr');
    }
    final theirTotalStr = isUsd
        ? CurrencyFormatter.toUsd(_theirTotal / exchangeRate)
        : CurrencyFormatter.toBrl(_theirTotal);
    buffer.writeln('${strings.totalReceived}: $theirTotalStr');

    final diffStr = isUsd
        ? CurrencyFormatter.toUsd(diff.abs() / exchangeRate)
        : CurrencyFormatter.toBrl(diff.abs());
    buffer.writeln('\n${strings.tradeDifferencePrefix}${diff >= 0 ? '+' : '-'}$diffStr');
    if (_yourTotal > 0) {
      final pct = ((diff / _yourTotal) * 100).abs();
      if (pct <= 5) {
        buffer.writeln('Status: ${strings.tradeStatusBalanced}');
      } else if (diff > 0) {
        buffer.writeln('Status: ${strings.tradeAdvantageous}');
      } else {
        buffer.writeln('Status: ${strings.tradeUnfavorable}');
      }
    }
    buffer.writeln('\nGenerated by WurmDex');

    Clipboard.setData(ClipboardData(text: buffer.toString()));
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(strings.tradeSummaryCopied)),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final language = ref.watch(languageProvider);
    final currency = ref.watch(currencyProvider);
    final strings = getStrings(language);
    final exchangeRate = ref.watch(exchangeRateProvider);
    final isUsd = currency == AppCurrency.usd;
    final diff = _theirTotal - _yourTotal;
    final totalSum = _yourTotal + _theirTotal;
    final diffPct = _yourTotal > 0 ? ((diff / _yourTotal) * 100) : 0.0;

    final diffFormatted = isUsd
        ? CurrencyFormatter.toUsd(diff.abs() / exchangeRate)
        : CurrencyFormatter.toBrl(diff.abs());

    Color statusColor;
    String statusText;
    if (totalSum == 0) {
      statusColor = Colors.grey;
      statusText = strings.tradePromptAddCards;
    } else if (diffPct.abs() <= 5) {
      statusColor = AppColors.profitGreen;
      statusText = strings.tradeStatusBalanced;
    } else if (diff > 0) {
      statusColor = AppColors.darkCyan;
      statusText = '${strings.tradeAdvantageous} (+$diffFormatted)';
    } else {
      statusColor = AppColors.warningYellow;
      statusText = '${strings.tradeUnfavorable} (-$diffFormatted)';
    }

    return Scaffold(
      appBar: AppBar(
        title: Text(strings.tradesTitle, style: const TextStyle(fontWeight: FontWeight.bold)),
        actions: [
          const AppOverflowMenu(showCurrency: true),
          const SizedBox(width: 4),
          IconButton(
            icon: const Icon(Icons.copy_all_outlined),
            tooltip: strings.copyTradeSummaryTooltip,
            onPressed: (_yourCards.isEmpty && _theirCards.isEmpty)
                ? null
                : () => _copyTradeSummary(strings, isUsd, exchangeRate),
          ),
          IconButton(
            icon: const Icon(Icons.delete_sweep_outlined),
            tooltip: strings.btnClearTrade,
            onPressed: (_yourCards.isNotEmpty || _theirCards.isNotEmpty)
                ? () {
                    setState(() {
                      _yourCards.clear();
                      _theirCards.clear();
                    });
                  }
                : null,
          ),
        ],
      ),
      body: Column(
        children: [
          // Equity Banner Header
          Container(
            width: double.infinity,
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            decoration: BoxDecoration(
              color: statusColor.withValues(alpha: 0.12),
              border: Border(bottom: BorderSide(color: statusColor.withValues(alpha: 0.3))),
            ),
            child: Column(
              children: [
                Text(
                  statusText,
                  style: TextStyle(
                    fontWeight: FontWeight.bold,
                    fontSize: 14,
                    color: statusColor,
                  ),
                  textAlign: TextAlign.center,
                ),
                if (totalSum > 0) ...[
                  const SizedBox(height: 4),
                  Text(
                    '${strings.tradeDifferencePrefix}${diff >= 0 ? '+' : '-'}$diffFormatted (${CurrencyFormatter.formatPercent(diffPct)})',
                    style: TextStyle(fontSize: 12, color: theme.colorScheme.onSurface.withValues(alpha: 0.7)),
                  ),
                ],
              ],
            ),
          ),

          // Two-Column Trade Board: Left = Send (Offer), Right = Receive (Get)
          Expanded(
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Left Column: You Send (Cartas a enviar)
                Expanded(
                  child: _buildTradeColumn(
                    context: context,
                    strings: strings,
                    title: strings.youSendTitle,
                    subtitle: strings.youSendSubtitle,
                    total: _yourTotal,
                    cards: _yourCards,
                    accentColor: theme.colorScheme.primary,
                    isUsd: isUsd,
                    exchangeRate: exchangeRate,
                    onAdd: () => _addYourCard(exchangeRate),
                    onRemove: (idx) => setState(() => _yourCards.removeAt(idx)),
                  ),
                ),
                const VerticalDivider(width: 1, thickness: 1),
                // Right Column: You Receive (Cartas a ganhar)
                Expanded(
                  child: _buildTradeColumn(
                    context: context,
                    strings: strings,
                    title: strings.youGetTitle,
                    subtitle: strings.youGetSubtitle,
                    total: _theirTotal,
                    cards: _theirCards,
                    accentColor: AppColors.profitGreen,
                    isUsd: isUsd,
                    exchangeRate: exchangeRate,
                    onAdd: () => _addTheirCard(exchangeRate),
                    onRemove: (idx) => setState(() => _theirCards.removeAt(idx)),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTradeColumn({
    required BuildContext context,
    required AppStrings strings,
    required String title,
    required String subtitle,
    required double total,
    required List<TradeCardItem> cards,
    required Color accentColor,
    required bool isUsd,
    required double exchangeRate,
    required VoidCallback onAdd,
    required ValueChanged<int> onRemove,
  }) {
    final theme = Theme.of(context);
    final totalDisplay = isUsd
        ? CurrencyFormatter.toUsd(total / exchangeRate)
        : CurrencyFormatter.toBrl(total);

    return Column(
      children: [
        // Column Header
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
          color: theme.cardColor,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      title,
                      style: TextStyle(fontWeight: FontWeight.bold, fontSize: 13, color: accentColor),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                    Text(
                      subtitle,
                      style: TextStyle(fontSize: 10, color: theme.colorScheme.onSurface.withValues(alpha: 0.6)),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                    const SizedBox(height: 2),
                    Text(
                      'Total: $totalDisplay',
                      style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 12),
                    ),
                  ],
                ),
              ),
              IconButton.filledTonal(
                icon: const Icon(Icons.add, size: 18),
                tooltip: strings.btnAddCard,
                onPressed: onAdd,
              ),
            ],
          ),
        ),
        const Divider(height: 1),

        // Cards List
        Expanded(
          child: cards.isEmpty
              ? Center(
                  child: Padding(
                    padding: const EdgeInsets.all(16),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(Icons.add_circle_outline, size: 36, color: theme.dividerColor),
                        const SizedBox(height: 8),
                        Text(
                          strings.noCardsAdded,
                          style: TextStyle(fontSize: 12, color: theme.colorScheme.onSurface.withValues(alpha: 0.5)),
                        ),
                        const SizedBox(height: 8),
                        OutlinedButton(
                          onPressed: onAdd,
                          child: Text(strings.btnAdd),
                        ),
                      ],
                    ),
                  ),
                )
              : ListView.separated(
                  padding: const EdgeInsets.all(8),
                  itemCount: cards.length,
                  separatorBuilder: (context, index) => const SizedBox(height: 6),
                  itemBuilder: (context, index) {
                    final card = cards[index];
                    final cardValStr = isUsd
                        ? CurrencyFormatter.toUsd(card.valueBrl / exchangeRate)
                        : CurrencyFormatter.toBrl(card.valueBrl);

                    return Card(
                      margin: EdgeInsets.zero,
                      child: ListTile(
                        dense: true,
                        contentPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                        leading: ClipRRect(
                          borderRadius: BorderRadius.circular(4),
                          child: CachedNetworkImage(
                            imageUrl: card.imageUrl,
                            width: 28,
                            height: 38,
                            fit: BoxFit.cover,
                            placeholder: (context, url) => const SizedBox(width: 28, height: 38),
                            errorWidget: (context, url, error) => const Icon(Icons.broken_image, size: 20),
                          ),
                        ),
                        title: Text(
                          card.name,
                          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 12),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                        ),
                        subtitle: Text(
                          card.setName,
                          style: TextStyle(fontSize: 10, color: theme.colorScheme.onSurface.withValues(alpha: 0.6)),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                        ),
                        trailing: Row(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Text(
                              cardValStr,
                              style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 11),
                            ),
                            IconButton(
                              icon: const Icon(Icons.close, size: 16),
                              tooltip: strings.remove,
                              onPressed: () => onRemove(index),
                            ),
                          ],
                        ),
                      ),
                    );
                  },
                ),
        ),
      ],
    );
  }
}
